name: Generate Space Shooter SVG

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare output directory
        run: mkdir -p output

      - name: Generate space shooter animation
        uses: czl9707/gh-space-shooter@main
        with:
          github-token: ${{ secrets.GH_PAT }}
          username: ${{ github.repository_owner }}
          output-path: output/space-shooter.webp
          no-amend: "true"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git diff --cached --quiet || git commit -m "chore: update space shooter"
          git push
